# This file is now only responsible for defining your application service.

# The database service has been removed because we are using AWS RDS.

version: '3.8'


services:

  app:

    # This tells Compose to build the image from the Dockerfile in the current directory.

    build: .

    

    # This now points to your specific image in the GitHub Container Registry.

    image: ghcr.io/wayfinder-625/prototype-1.1-backend:latest

    

    # This file, which you will place on your server, contains all your secrets.

    env_file:

      - .env.prod

    

    ports:

      # Maps the public port 80 on the server to your app's port 3000 inside the container.

      - "80:3000"

      

    # Ensures the container restarts automatically if it crashes or the server reboots.

    restart: unless-stopped